### ISSUE TITLE
Liquid branch testnet

### ISSUE THREAD

**Issue by BHodl** [SatoshiPortal/cyphernode#235]
When selecting testnet as network on liquid branch, elements is configured as regtest.

**Comment by Kexkey** [comment]
There's no testnet on liquid :)

There is liquidv1 (mainnet) and elementsregtest (regtest for elements).  There is now also signet if I'm not mistaken... haven't tried it yet.

**Comment by BHodl** [comment]
Look like it exist now. https://blockstream.info/liquidtestnet/blocks/recent I managed to make it work with elements-qt but no success with peg-in for now. Configuration and faucet --> https://liquidtestnet.com

**Comment by Kexkey** [comment]
Oh wow!  I wasn't aware they finally created one!  Thanks!  I'll update the `features/liquid` branch!

**Comment by i5hi** [comment]
@BHodl Have you had any success with this? I am trying to get this working as well.

**Comment by i5hi** [comment]
> Look like it exist now. https://blockstream.info/liquidtestnet/blocks/recent I managed to make it work with elements-qt but no success with peg-in for now. Configuration and faucet --> https://liquidtestnet.com

Still figuring this out myself. FWIU LiquidTestnet is maintained by Blockstream and not actually linked to BitcoinTestnet - so no peg-ins.

**Comment by i5hi** [comment]
@BHodl

The reason why it doesn't work is because the `liquidtestnet.com` config has the setting `daemon=1` 
Container needs the process to stay in the foreground.

**Comment by i5hi** [comment]
I got it working with this docker-compose.yaml

```yaml
  elements_liquidtestnet:
    image: cyphernode/elements:v22.0.2-mosquitto-debian
    user: $USER
    command: elementsd
    ports:
      - 18891:18891
    volumes:
      - "/mnt/sharednodes/elements_liquidtestnet:/.elements"
    stop_grace_period: 30s
    networks:
      - sharednodesnet
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.io.sharednodes == true
      restart_policy:
        condition: "any"
        delay: 1s
      update_config:
        parallelism: 1
```
